# Generated by Django 5.1.4 on 2025-01-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français')], max_length=2, null=True),
        ),
    ]
